name: znn_htlc_test
description: Test HTLCs on NoM
version: 0.0.5
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^1.7.1
  znn_sdk_dart:
    git:
      url: https://github.com/sol-sanctum/znn_sdk_dart.git
      ref: spork_htlc

dev_dependencies:
  test: ^1.17.9
  lints: ^1.0.1
